### ISSUE TITLE
Webpack build fails (react-scripts 0.9.5)

### ISSUE THREAD

**Issue by DawidLoubser** [jsdom/whatwg-url#102]
When importing and using `URL` in an app created with `create-react-app`, building a production app fails with:

```
> react-scripts build

Creating an optimized production build...
Failed to compile.

static/js/main.38ef0137.js from UglifyJs
SyntaxError: Name expected [./~/whatwg-url/lib/url-state-machine.js:6,0]
```

**Comment by domenic** [comment]
Sounds like you should file a bug with webpack.

**Comment by DawidLoubser** [comment]
For anybody also stuck with this issue, I switched to a different, but API-compatible for my purposes of URL parsing - library called [url-parse](https://github.com/unshiftio/url-parse) and the problem no longer occurs.

**Comment by stevenvachon** [comment]
That library is not API-compatible.

**Comment by DawidLoubser** [comment]
I believe I *did* qualify it with **for my purposes**, and elaborated on that purpose (URL parsing).
I swapped out the npm dependency, and didn't have to change any code.

**Comment by stevenvachon** [comment]
Re-read my comment. I edited it before you responded. That library is not spec-compliant and can cause issues for you in the future. Purposes change.

**Comment by khalsah** [comment]
I'm seeing this same issue. It appears the underlying cause is that whatwg-url uses ES6 syntax in it's final distributed form, while current versions of uglify-js only supports ES5.

This also makes this library problematic for use as a polyfill for `URL` since browsers that don't support `URL` natively are unlikely to support the necessary ES6 constructs used in this library.

The current norm in my circles, problematic though it may be, seems to be to assume that the module authors will perform any required transpilation and will distribute ES5 compatible sources.

**Comment by stevenvachon** [comment]
[universal-url](https://npmjs.com/universal-url) wraps this library to provide browser support.

**Comment by stevenvachon** [comment]
This library was written for [jsdom](https://npmjs.com/jsdom). This module does not claim to be universal/isomorphic, so if you want it to run in a browser, you'll need to transpile it yourself.

**Comment by khalsah** [comment]
:+1: @stevenvachon Thanks for the clarification.

(Might be worth pointing towards universal-url in the README for others who make the same bad assumption I did).

**Comment by stevenvachon** [comment]
I think @domenic is against mentioning other projects in general.
