### ISSUE TITLE
Update for latest URL spec changes

### ISSUE THREAD

**Issue by domenic** [jsdom/whatwg-url#11]
Anne's back from vacation and things are changing!!

https://github.com/whatwg/url/compare/06b2e6895dff2e6efaeba65f4eb1bc27ecc21581...master

Changes to exact set of characters that are encoded, basically.

I think we should not do this without adding our own supplement to web-platform-tests for each case (in this repo).

**Comment by Sebmaster** [comment]
Added the chars to the encode set, but not published yet. I think we need to rewrite the encoding to be just a single `encode` function which is given differing input encoding sets. This would make the encoding functions much less error prone since they're currently copy&paste'd a lot.

Also still need the tests for it. I guess it'd be best to contribute those directly to web-platform-tests?

**Comment by domenic** [comment]
I think we should set up a way to create a supplementary test-data file and run/develop that locally, then contribute back over time. I want to avoid blocking on them merging things.

**Comment by Sebmaster** [comment]
Nice, testing this led me to another issue with the spec ([whatwg-url#29](https://github.com/whatwg/url/issues/28)), since we're currently only default encoding username and password during initial url parsing.
