### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by AustinFRG** [jsdom/whatwg-url#235]
0|app  | ReferenceError: TextEncoder is not defined
0|app  |     at Object.<anonymous> (/root/Discord Bots/HyperSpeed/node_modules/whatwg-url/lib/encoding.js:2:21)
0|app  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|app  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|app  |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|app  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|app  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|app  |     at Module.require (internal/modules/cjs/loader.js:692:17)
0|app  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|app  |     at require (internal/modules/cjs/helpers.js:25:18)
0|app  |     at Object.<anonymous> (/root/Discord Bots/HyperSpeed/node_modules/whatwg-url/lib/url-state-machine.js:5:34)

**Comment by AustinFRG** [comment]
Can be fixed by adding `const { TextEncoder, TextDecoder } = require("util");` to encoding.js

**Comment by domenic** [comment]
See closed issues and PRs, your Node.js version is too low.

**Comment by speedytwenty** [comment]
> See closed issues and PRs, your Node.js version is too low.

This is unacceptable. First, the version in package.json claims support is for `node": ">=12"`. Second, we're talking one line to solve the issue—and you're neglecting all the packages that depend on this one. It's not feasible and utterly ridiculous to impose this.

Maybe I'm missing something.. but do you have one good reason why you're forcing people through complicated environment issues rather than simply solving the issue?
