### ISSUE TITLE
Cannot convert undefined or null to object         at Function.getPrototypeOf

### ISSUE THREAD

**Issue by intrepidOlivia** [jsdom/whatwg-url#276]
I found [this issue](https://github.com/jsdom/whatwg-url/issues/274) while I was looking for a solution to this error I ran into.

This error occurs when I try to import the whatwg-url library into my unit tests.

```
    TypeError: Cannot convert undefined or null to object
        at Function.getPrototypeOf (<anonymous>)
      at Object.<anonymous> (node_modules/whatwg-url/dist/utils.js:48:39)
      at Object.<anonymous> (node_modules/whatwg-url/dist/URL.js:4:15)
      at Object.<anonymous> (node_modules/whatwg-url/webidl2js-wrapper.js:3:13)
      at Object.<anonymous> (node_modules/whatwg-url/index.js:3:34)
      at Object.<anonymous> (test/sample_test.spec.ts:1:1)
```

I have a minimal test case for this error. There must be something about it that makes it an edge case, since this error doesn't seem to have caused too many problems in the dev community since version 8 was released. But in my current project it is preventing me updating this library to the most recent version.

Minimal test case: https://github.com/intrepidOlivia/whatwg_test_case

_Originally posted by @intrepidOlivia in https://github.com/jsdom/whatwg-url/issues/274#issuecomment-2291679556_

**Comment by domenic** [comment]
Closing per https://github.com/jsdom/whatwg-url/issues/274#issuecomment-2292599499

**Comment by ahmed-musallam** [comment]
FYI for anyone that arrives here...

My specific issue here was how webpack/babel polyfilled async generators:
https://babeljs.io/docs/babel-plugin-transform-async-to-generator

In my case, I had no control over babel transforms, but I could change webpack configs.

I was already using [esbuild-loader,](https://www.npmjs.com/package/esbuild-loader) so I set the `target` option to `es2020` since my code will run on node 22, which already implements async generators (no need for babel to transform it)

That fixed my issue.

Whatever build tool you are using, it might be transforming async generators, so make sure the target output is `es2020` so long as your runtime implements es2020 :)
