### ISSUE TITLE
Deprecation issue with the 'punycode' module

### ISSUE THREAD

**Issue by valorisa** [jsdom/whatwg-url#278]
Hello,

I am encountering a deprecation issue with the punycode module in your project. The warning message is as follows:

(node:19880) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.

Could you consider updating your project to use a more recent version of punycode (e.g., punycode@2.3.1)?

Thank you in advance for your help.

Best regards,
valorisa

**Comment by domenic** [comment]
This is not related to this project.

**Comment by NullVoxPopuli** [comment]
it _used to be_ though.
https://github.com/jsdom/whatwg-url/blob/v8.7.0/src/url-state-machine.js#L2

people probably need to set overrides in their projects, or PR to the dependencies using whatwg-url and update them.

**Comment by arminrosu** [comment]
> This is not related to this project.

@domenic I agree this is not related to the project and caused by a 8 year old version of this package. I, and likely many others, would highly appreciate a patch release though.

`node-fetch@2.7.0` depends on `whatwg-url@^5.0.0` and the former is used extensively.

The required change is minimal IMO:

lib/url-state-machine.js:
```diff
- const punycode = require('punycode')
+ const punycode = require('punycode/')
```

package.json:
```diff
"dependencies": {
+  "punycode": "2.3.1",
```

`tr46` has the same issue and resolution. I'm going to go with patching the node_modules (maybe via [patch-package](https://www.npmjs.com/package/patch-package) ).

I fully understand if you don't want to patch v5.0.0 and we do have a resolution. Would be really nice though.

**Comment by domenic** [comment]
Sorry, we have no plans to support old versions of this project; maintaining just one is enough for us.
