### ISSUE TITLE
Host is dropped if path contains colon

### ISSUE THREAD

**Issue by felixfbecker** [jsdom/whatwg-url#84]
`file://` URLs on Windows typically do not %-encode the colon after the drive letter. When building such URIs, this library drops the host of the base (I assume because it reads it as a port?)

Expected, Chrome:
```js
new URL('/c:/baz/qux', 'file://host/foo/bar').href
"file://host/c:/baz/qux"
```

Actual, whatwg-url:
```js
new URL('/c:/baz/qux', 'file://host/foo/bar').href
"file:///c:/baz/qux"
```

It actually happens even when you just set `pathname` to anything with a colon:
```js
const uri = new URL('file://host/foo')
uri.host // 'host'
uri.pathname = '/c:/bar'
uri.host // ''
```

**Comment by Sebmaster** [comment]
Looks to me like that is because in the URL spec in the [path state](https://url.spec.whatwg.org/#path-state) instruction 1.4.1.1 does not use the base URL host.

Open a bug in the [official repo](https://github.com/whatwg/url) if you think that's a bug in the spec.
Closing because I don't think that's a bug in whatwg-url, but can reopen if you think I followed the spec wrong.

**Comment by felixfbecker** [comment]
Opened https://github.com/whatwg/url/issues/302
